2021-09-09 19:52:07.989 CDT [5932] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-09 19:52:08.027 CDT [5932] LOG:  listening on IPv6 address "::1", port 5432
2021-09-09 19:52:08.027 CDT [5932] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-09 19:52:08.042 CDT [5932] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-09 19:52:08.307 CDT [5933] LOG:  database system was interrupted; last known up at 2021-09-08 17:35:03 CDT
2021-09-09 19:52:09.495 CDT [5933] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-09 19:52:09.520 CDT [5933] LOG:  redo starts at 0/1629AE0
2021-09-09 19:52:09.520 CDT [5933] LOG:  invalid record length at 0/1629BC8: wanted 24, got 0
2021-09-09 19:52:09.520 CDT [5933] LOG:  redo done at 0/1629B90
2021-09-09 19:52:09.585 CDT [5932] LOG:  database system is ready to accept connections
2021-09-10 01:30:29.577 CDT [4414] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-10 01:30:29.660 CDT [4414] LOG:  listening on IPv6 address "::1", port 5432
2021-09-10 01:30:29.660 CDT [4414] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-10 01:30:29.676 CDT [4414] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-10 01:30:30.152 CDT [4415] LOG:  database system was interrupted; last known up at 2021-09-09 20:22:34 CDT
2021-09-10 01:30:32.411 CDT [4415] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-10 01:30:32.443 CDT [4415] LOG:  redo starts at 0/169BDD0
2021-09-10 01:30:32.443 CDT [4415] LOG:  invalid record length at 0/169BEB8: wanted 24, got 0
2021-09-10 01:30:32.443 CDT [4415] LOG:  redo done at 0/169BE80
2021-09-10 01:30:32.497 CDT [4414] LOG:  database system is ready to accept connections
2021-09-10 18:23:16.361 CDT [5067] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-10 18:23:16.416 CDT [5067] LOG:  listening on IPv6 address "::1", port 5432
2021-09-10 18:23:16.416 CDT [5067] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-10 18:23:16.417 CDT [5067] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-10 18:23:16.739 CDT [5071] LOG:  database system was interrupted; last known up at 2021-09-10 01:30:32 CDT
2021-09-10 18:23:18.323 CDT [5071] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-10 18:23:18.359 CDT [5071] LOG:  redo starts at 0/169BF30
2021-09-10 18:23:18.359 CDT [5071] LOG:  invalid record length at 0/169BF68: wanted 24, got 0
2021-09-10 18:23:18.359 CDT [5071] LOG:  redo done at 0/169BF30
2021-09-10 18:23:18.401 CDT [5067] LOG:  database system is ready to accept connections
2021-09-11 17:12:13.823 CDT [4062] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-11 17:12:13.904 CDT [4062] LOG:  listening on IPv6 address "::1", port 5432
2021-09-11 17:12:13.904 CDT [4062] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-11 17:12:14.054 CDT [4062] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-11 17:12:14.669 CDT [4063] LOG:  database system was interrupted; last known up at 2021-09-11 02:15:55 CDT
2021-09-11 17:12:16.897 CDT [4063] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-11 17:12:17.020 CDT [4063] LOG:  redo starts at 0/16C4208
2021-09-11 17:12:17.020 CDT [4063] LOG:  invalid record length at 0/16C42F0: wanted 24, got 0
2021-09-11 17:12:17.020 CDT [4063] LOG:  redo done at 0/16C42B8
2021-09-11 17:12:17.235 CDT [4062] LOG:  database system is ready to accept connections
2021-09-11 20:07:52.426 CDT [7708] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:07:52.426 CDT [7708] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:12:03.267 CDT [7708] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:12:03.267 CDT [7708] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:18:32.239 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:18:32.239 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:18:49.544 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:18:49.544 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:18:56.204 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:18:56.204 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:19:23.880 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:19:23.880 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:19:31.354 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:19:31.354 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:20:05.889 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:20:05.889 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:20:49.501 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:20:49.501 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:21:06.421 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:21:06.421 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:21:33.463 CDT [8273] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:21:33.463 CDT [8273] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:21:54.798 CDT [8273] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:21:54.798 CDT [8273] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:35:34.500 CDT [8584] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:35:34.500 CDT [8584] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:37:00.421 CDT [8584] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:37:00.421 CDT [8584] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:47:25.215 CDT [8913] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:47:25.215 CDT [8913] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:51:20.045 CDT [8913] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:51:20.045 CDT [8913] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:05:33.527 CDT [9381] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:05:33.527 CDT [9381] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:11:39.951 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:11:39.951 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:12:07.281 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:12:07.281 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:12:54.583 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:12:54.583 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:13:01.907 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:13:01.907 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:14:47.167 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:14:47.167 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:15:01.227 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:15:01.227 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:16:19.057 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:16:19.057 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:17:08.828 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:17:08.828 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-12 16:02:37.464 CDT [5264] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-12 16:02:37.773 CDT [5264] LOG:  listening on IPv6 address "::1", port 5432
2021-09-12 16:02:37.773 CDT [5264] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-12 16:02:37.775 CDT [5264] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-12 16:02:38.232 CDT [5265] LOG:  database system was interrupted; last known up at 2021-09-11 17:12:17 CDT
2021-09-12 16:02:38.781 CDT [5265] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-12 16:02:38.828 CDT [5265] LOG:  redo starts at 0/16C4368
2021-09-12 16:02:38.828 CDT [5265] LOG:  invalid record length at 0/16C43A0: wanted 24, got 0
2021-09-12 16:02:38.828 CDT [5265] LOG:  redo done at 0/16C4368
2021-09-12 16:02:38.860 CDT [5264] LOG:  database system is ready to accept connections
2021-09-14 14:03:26.293 CDT [10230] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-14 14:03:26.347 CDT [10230] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-14 14:03:26.348 CDT [10230] LOG:  listening on IPv6 address "::1", port 5432
2021-09-14 14:03:26.349 CDT [10230] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-14 14:03:26.722 CDT [10234] LOG:  database system was interrupted; last known up at 2021-09-12 19:02:39 CDT
2021-09-14 14:03:27.353 CDT [10234] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-14 14:03:27.434 CDT [10234] LOG:  redo starts at 0/16D22D8
2021-09-14 14:03:27.435 CDT [10234] LOG:  invalid record length at 0/16D23C0: wanted 24, got 0
2021-09-14 14:03:27.435 CDT [10234] LOG:  redo done at 0/16D2388
2021-09-14 14:03:27.555 CDT [10230] LOG:  database system is ready to accept connections
2021-09-14 23:25:05.110 CDT [4941] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-14 23:25:05.230 CDT [4941] LOG:  listening on IPv6 address "::1", port 5432
2021-09-14 23:25:05.230 CDT [4941] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-14 23:25:05.261 CDT [4941] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-14 23:25:05.874 CDT [4942] LOG:  database system was interrupted; last known up at 2021-09-14 14:03:27 CDT
2021-09-14 23:25:07.406 CDT [4942] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-14 23:25:07.541 CDT [4942] LOG:  redo starts at 0/16D2438
2021-09-14 23:25:07.541 CDT [4942] LOG:  invalid record length at 0/16D2470: wanted 24, got 0
2021-09-14 23:25:07.541 CDT [4942] LOG:  redo done at 0/16D2438
2021-09-14 23:25:07.584 CDT [4941] LOG:  database system is ready to accept connections
2021-09-15 01:25:15.274 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:25:15.274 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:25:27.185 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:25:27.185 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:25:28.261 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:25:28.261 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:25:29.004 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:25:29.004 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:26:16.214 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:26:16.214 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:26:17.054 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:26:17.054 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:26:17.863 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:26:17.863 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:28:37.220 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:28:37.220 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:28:38.339 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:28:38.339 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:40.567 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:40.567 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:41.729 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:41.729 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:42.763 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:42.763 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:43.514 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:43.514 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:44.083 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:44.083 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:44.496 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:44.496 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:44.848 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:44.848 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:30:52.079 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:30:52.079 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:30:54.921 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:30:54.921 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:30:55.752 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:30:55.752 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:30:56.661 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:30:56.661 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:41:54.832 CDT [9581] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:41:54.832 CDT [9581] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
