2021-09-09 19:52:07.989 CDT [5932] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-09 19:52:08.027 CDT [5932] LOG:  listening on IPv6 address "::1", port 5432
2021-09-09 19:52:08.027 CDT [5932] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-09 19:52:08.042 CDT [5932] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-09 19:52:08.307 CDT [5933] LOG:  database system was interrupted; last known up at 2021-09-08 17:35:03 CDT
2021-09-09 19:52:09.495 CDT [5933] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-09 19:52:09.520 CDT [5933] LOG:  redo starts at 0/1629AE0
2021-09-09 19:52:09.520 CDT [5933] LOG:  invalid record length at 0/1629BC8: wanted 24, got 0
2021-09-09 19:52:09.520 CDT [5933] LOG:  redo done at 0/1629B90
2021-09-09 19:52:09.585 CDT [5932] LOG:  database system is ready to accept connections
2021-09-10 01:30:29.577 CDT [4414] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-10 01:30:29.660 CDT [4414] LOG:  listening on IPv6 address "::1", port 5432
2021-09-10 01:30:29.660 CDT [4414] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-10 01:30:29.676 CDT [4414] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-10 01:30:30.152 CDT [4415] LOG:  database system was interrupted; last known up at 2021-09-09 20:22:34 CDT
2021-09-10 01:30:32.411 CDT [4415] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-10 01:30:32.443 CDT [4415] LOG:  redo starts at 0/169BDD0
2021-09-10 01:30:32.443 CDT [4415] LOG:  invalid record length at 0/169BEB8: wanted 24, got 0
2021-09-10 01:30:32.443 CDT [4415] LOG:  redo done at 0/169BE80
2021-09-10 01:30:32.497 CDT [4414] LOG:  database system is ready to accept connections
2021-09-10 18:23:16.361 CDT [5067] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-10 18:23:16.416 CDT [5067] LOG:  listening on IPv6 address "::1", port 5432
2021-09-10 18:23:16.416 CDT [5067] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-10 18:23:16.417 CDT [5067] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-10 18:23:16.739 CDT [5071] LOG:  database system was interrupted; last known up at 2021-09-10 01:30:32 CDT
2021-09-10 18:23:18.323 CDT [5071] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-10 18:23:18.359 CDT [5071] LOG:  redo starts at 0/169BF30
2021-09-10 18:23:18.359 CDT [5071] LOG:  invalid record length at 0/169BF68: wanted 24, got 0
2021-09-10 18:23:18.359 CDT [5071] LOG:  redo done at 0/169BF30
2021-09-10 18:23:18.401 CDT [5067] LOG:  database system is ready to accept connections
2021-09-11 17:12:13.823 CDT [4062] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-11 17:12:13.904 CDT [4062] LOG:  listening on IPv6 address "::1", port 5432
2021-09-11 17:12:13.904 CDT [4062] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-11 17:12:14.054 CDT [4062] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-11 17:12:14.669 CDT [4063] LOG:  database system was interrupted; last known up at 2021-09-11 02:15:55 CDT
2021-09-11 17:12:16.897 CDT [4063] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-11 17:12:17.020 CDT [4063] LOG:  redo starts at 0/16C4208
2021-09-11 17:12:17.020 CDT [4063] LOG:  invalid record length at 0/16C42F0: wanted 24, got 0
2021-09-11 17:12:17.020 CDT [4063] LOG:  redo done at 0/16C42B8
2021-09-11 17:12:17.235 CDT [4062] LOG:  database system is ready to accept connections
2021-09-11 20:07:52.426 CDT [7708] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:07:52.426 CDT [7708] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:12:03.267 CDT [7708] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:12:03.267 CDT [7708] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:18:32.239 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:18:32.239 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:18:49.544 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:18:49.544 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:18:56.204 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:18:56.204 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:19:23.880 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:19:23.880 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:19:31.354 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:19:31.354 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:20:05.889 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:20:05.889 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:20:49.501 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:20:49.501 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:21:06.421 CDT [8081] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:21:06.421 CDT [8081] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:21:33.463 CDT [8273] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:21:33.463 CDT [8273] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:21:54.798 CDT [8273] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:21:54.798 CDT [8273] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:35:34.500 CDT [8584] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:35:34.500 CDT [8584] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:37:00.421 CDT [8584] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:37:00.421 CDT [8584] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:47:25.215 CDT [8913] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:47:25.215 CDT [8913] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 20:51:20.045 CDT [8913] ERROR:  column users.category_id does not exist at character 40
2021-09-11 20:51:20.045 CDT [8913] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:05:33.527 CDT [9381] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:05:33.527 CDT [9381] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:11:39.951 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:11:39.951 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:12:07.281 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:12:07.281 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:12:54.583 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:12:54.583 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:13:01.907 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:13:01.907 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:14:47.167 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:14:47.167 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:15:01.227 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:15:01.227 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:16:19.057 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:16:19.057 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-11 21:17:08.828 CDT [9503] ERROR:  column users.category_id does not exist at character 40
2021-09-11 21:17:08.828 CDT [9503] STATEMENT:  SELECT "users"."id" FROM "users" WHERE "users"."category_id" = $1
2021-09-12 16:02:37.464 CDT [5264] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-12 16:02:37.773 CDT [5264] LOG:  listening on IPv6 address "::1", port 5432
2021-09-12 16:02:37.773 CDT [5264] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-12 16:02:37.775 CDT [5264] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-12 16:02:38.232 CDT [5265] LOG:  database system was interrupted; last known up at 2021-09-11 17:12:17 CDT
2021-09-12 16:02:38.781 CDT [5265] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-12 16:02:38.828 CDT [5265] LOG:  redo starts at 0/16C4368
2021-09-12 16:02:38.828 CDT [5265] LOG:  invalid record length at 0/16C43A0: wanted 24, got 0
2021-09-12 16:02:38.828 CDT [5265] LOG:  redo done at 0/16C4368
2021-09-12 16:02:38.860 CDT [5264] LOG:  database system is ready to accept connections
2021-09-14 14:03:26.293 CDT [10230] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-14 14:03:26.347 CDT [10230] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-14 14:03:26.348 CDT [10230] LOG:  listening on IPv6 address "::1", port 5432
2021-09-14 14:03:26.349 CDT [10230] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-14 14:03:26.722 CDT [10234] LOG:  database system was interrupted; last known up at 2021-09-12 19:02:39 CDT
2021-09-14 14:03:27.353 CDT [10234] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-14 14:03:27.434 CDT [10234] LOG:  redo starts at 0/16D22D8
2021-09-14 14:03:27.435 CDT [10234] LOG:  invalid record length at 0/16D23C0: wanted 24, got 0
2021-09-14 14:03:27.435 CDT [10234] LOG:  redo done at 0/16D2388
2021-09-14 14:03:27.555 CDT [10230] LOG:  database system is ready to accept connections
2021-09-14 23:25:05.110 CDT [4941] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-14 23:25:05.230 CDT [4941] LOG:  listening on IPv6 address "::1", port 5432
2021-09-14 23:25:05.230 CDT [4941] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-14 23:25:05.261 CDT [4941] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-14 23:25:05.874 CDT [4942] LOG:  database system was interrupted; last known up at 2021-09-14 14:03:27 CDT
2021-09-14 23:25:07.406 CDT [4942] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-14 23:25:07.541 CDT [4942] LOG:  redo starts at 0/16D2438
2021-09-14 23:25:07.541 CDT [4942] LOG:  invalid record length at 0/16D2470: wanted 24, got 0
2021-09-14 23:25:07.541 CDT [4942] LOG:  redo done at 0/16D2438
2021-09-14 23:25:07.584 CDT [4941] LOG:  database system is ready to accept connections
2021-09-15 01:25:15.274 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:25:15.274 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:25:27.185 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:25:27.185 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:25:28.261 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:25:28.261 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:25:29.004 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:25:29.004 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:26:16.214 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:26:16.214 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:26:17.054 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:26:17.054 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:26:17.863 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:26:17.863 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:28:37.220 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:28:37.220 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:28:38.339 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:28:38.339 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:40.567 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:40.567 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:41.729 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:41.729 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:42.763 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:42.763 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:43.514 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:43.514 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:44.083 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:44.083 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:44.496 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:44.496 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:29:44.848 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:29:44.848 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:30:52.079 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:30:52.079 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:30:54.921 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:30:54.921 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:30:55.752 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:30:55.752 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:30:56.661 CDT [8211] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:30:56.661 CDT [8211] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 01:41:54.832 CDT [9581] ERROR:  column categories.user_id does not exist at character 50
2021-09-15 01:41:54.832 CDT [9581] STATEMENT:  SELECT "categories"."id" FROM "categories" WHERE "categories"."user_id" = $1
2021-09-15 16:53:07.179 CDT [3998] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-15 16:53:07.895 CDT [3998] LOG:  listening on IPv6 address "::1", port 5432
2021-09-15 16:53:07.895 CDT [3998] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-15 16:53:07.897 CDT [3998] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-15 16:53:08.509 CDT [4001] LOG:  database system was interrupted; last known up at 2021-09-15 00:00:08 CDT
2021-09-15 16:53:09.619 CDT [4001] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-15 16:53:09.721 CDT [4001] LOG:  redo starts at 0/16DA238
2021-09-15 16:53:09.721 CDT [4001] LOG:  invalid record length at 0/16DA320: wanted 24, got 0
2021-09-15 16:53:09.721 CDT [4001] LOG:  redo done at 0/16DA2E8
2021-09-15 16:53:09.790 CDT [3998] LOG:  database system is ready to accept connections
2021-09-16 01:34:03.372 CDT [3690] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-16 01:34:03.431 CDT [3690] LOG:  listening on IPv6 address "::1", port 5432
2021-09-16 01:34:03.431 CDT [3690] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-16 01:34:03.452 CDT [3690] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-16 01:34:04.012 CDT [3691] LOG:  database system was interrupted; last known up at 2021-09-15 21:55:30 CDT
2021-09-16 01:34:05.218 CDT [3691] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-16 01:34:05.281 CDT [3691] LOG:  redo starts at 0/16DB660
2021-09-16 01:34:05.281 CDT [3691] LOG:  invalid record length at 0/16DB748: wanted 24, got 0
2021-09-16 01:34:05.281 CDT [3691] LOG:  redo done at 0/16DB710
2021-09-16 01:34:05.336 CDT [3690] LOG:  database system is ready to accept connections
2021-09-16 23:52:11.785 CDT [3686] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-16 23:52:12.140 CDT [3686] LOG:  listening on IPv6 address "::1", port 5432
2021-09-16 23:52:12.140 CDT [3686] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-16 23:52:12.141 CDT [3686] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-16 23:52:12.525 CDT [3687] LOG:  database system was interrupted; last known up at 2021-09-16 01:34:05 CDT
2021-09-16 23:52:13.521 CDT [3687] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-16 23:52:13.575 CDT [3687] LOG:  redo starts at 0/16DB7C0
2021-09-16 23:52:13.575 CDT [3687] LOG:  invalid record length at 0/16DB7F8: wanted 24, got 0
2021-09-16 23:52:13.575 CDT [3687] LOG:  redo done at 0/16DB7C0
2021-09-16 23:52:13.657 CDT [3686] LOG:  database system is ready to accept connections
2021-09-17 01:49:49.421 CDT [5239] ERROR:  database "ManyProjects_development" is being accessed by other users
2021-09-17 01:49:49.421 CDT [5239] DETAIL:  There are 2 other sessions using the database.
2021-09-17 01:49:49.421 CDT [5239] STATEMENT:  DROP DATABASE IF EXISTS "ManyProjects_development"
2021-09-17 01:55:17.374 CDT [5319] FATAL:  database "ManyProjects_development" does not exist
2021-09-17 03:00:00.991 CDT [5778] ERROR:  database "ManyProjects_development" is being accessed by other users
2021-09-17 03:00:00.991 CDT [5778] DETAIL:  There are 2 other sessions using the database.
2021-09-17 03:00:00.991 CDT [5778] STATEMENT:  DROP DATABASE IF EXISTS "ManyProjects_development"
2021-09-17 03:04:25.883 CDT [5822] FATAL:  database "ManyProjects_development" does not exist
2021-09-17 23:15:22.084 CDT [7591] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-17 23:15:22.267 CDT [7591] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-17 23:15:22.267 CDT [7591] LOG:  listening on IPv6 address "::1", port 5432
2021-09-17 23:15:22.267 CDT [7591] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-17 23:15:22.891 CDT [7597] LOG:  database system was interrupted; last known up at 2021-09-17 03:19:43 CDT
2021-09-17 23:15:23.989 CDT [7597] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-17 23:15:24.030 CDT [7597] LOG:  redo starts at 0/17BC0E8
2021-09-17 23:15:24.030 CDT [7597] LOG:  invalid record length at 0/17BC1D0: wanted 24, got 0
2021-09-17 23:15:24.030 CDT [7597] LOG:  redo done at 0/17BC198
2021-09-17 23:15:24.079 CDT [7591] LOG:  database system is ready to accept connections
2021-09-20 00:49:08.382 CDT [4009] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-20 00:49:08.526 CDT [4009] LOG:  listening on IPv6 address "::1", port 5432
2021-09-20 00:49:08.526 CDT [4009] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-20 00:49:08.527 CDT [4009] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-20 00:49:09.034 CDT [4010] LOG:  database system was interrupted; last known up at 2021-09-17 23:15:24 CDT
2021-09-20 00:49:09.634 CDT [4010] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-20 00:49:09.657 CDT [4010] LOG:  redo starts at 0/17BC248
2021-09-20 00:49:09.657 CDT [4010] LOG:  invalid record length at 0/17BC280: wanted 24, got 0
2021-09-20 00:49:09.657 CDT [4010] LOG:  redo done at 0/17BC248
2021-09-20 00:49:09.734 CDT [4009] LOG:  database system is ready to accept connections
2021-09-20 19:54:55.520 CDT [4700] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-20 19:54:55.641 CDT [4700] LOG:  listening on IPv6 address "::1", port 5432
2021-09-20 19:54:55.641 CDT [4700] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-20 19:54:55.642 CDT [4700] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-20 19:54:55.949 CDT [4704] LOG:  database system was interrupted; last known up at 2021-09-20 00:49:09 CDT
2021-09-20 19:54:56.296 CDT [4704] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-20 19:54:56.317 CDT [4704] LOG:  redo starts at 0/17BC2F8
2021-09-20 19:54:56.317 CDT [4704] LOG:  invalid record length at 0/17BC330: wanted 24, got 0
2021-09-20 19:54:56.317 CDT [4704] LOG:  redo done at 0/17BC2F8
2021-09-20 19:54:56.360 CDT [4700] LOG:  database system is ready to accept connections
2021-09-21 14:30:50.977 CDT [3829] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-21 14:30:51.401 CDT [3829] LOG:  listening on IPv6 address "::1", port 5432
2021-09-21 14:30:51.401 CDT [3829] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-21 14:30:51.733 CDT [3829] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-21 14:30:53.303 CDT [3832] LOG:  database system was interrupted; last known up at 2021-09-20 19:54:56 CDT
2021-09-21 14:30:56.429 CDT [3832] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-21 14:30:57.030 CDT [3832] LOG:  redo starts at 0/17BC3A8
2021-09-21 14:30:57.030 CDT [3832] LOG:  invalid record length at 0/17BC3E0: wanted 24, got 0
2021-09-21 14:30:57.030 CDT [3832] LOG:  redo done at 0/17BC3A8
2021-09-21 14:30:57.969 CDT [3829] LOG:  database system is ready to accept connections
2021-09-22 15:56:16.702 CDT [3893] FATAL:  lock file "postmaster.pid" already exists
2021-09-22 15:56:16.702 CDT [3893] HINT:  Is another postmaster (PID 3829) running in data directory "/usr/local/var/postgres_dev"?
2021-09-22 16:34:37.153 CDT [4741] FATAL:  lock file "postmaster.pid" already exists
2021-09-22 16:34:37.153 CDT [4741] HINT:  Is another postmaster (PID 3829) running in data directory "/usr/local/var/postgres_dev"?
2021-09-22 16:36:05.191 CDT [4757] FATAL:  lock file "postmaster.pid" already exists
2021-09-22 16:36:05.191 CDT [4757] HINT:  Is another postmaster (PID 3829) running in data directory "/usr/local/var/postgres_dev"?
2021-09-22 16:40:57.281 CDT [5587] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-22 16:40:57.348 CDT [5587] LOG:  listening on IPv6 address "::1", port 5432
2021-09-22 16:40:57.348 CDT [5587] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-22 16:40:57.369 CDT [5587] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-22 16:40:57.767 CDT [5591] LOG:  database system was interrupted; last known up at 2021-09-21 21:25:34 CDT
2021-09-22 16:40:58.346 CDT [5591] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-22 16:40:58.434 CDT [5591] LOG:  redo starts at 0/17BCE10
2021-09-22 16:40:58.434 CDT [5591] LOG:  invalid record length at 0/17BCEF8: wanted 24, got 0
2021-09-22 16:40:58.434 CDT [5591] LOG:  redo done at 0/17BCEC0
2021-09-22 16:40:58.487 CDT [5587] LOG:  database system is ready to accept connections
2021-09-22 16:46:51.293 CDT [5587] LOG:  received fast shutdown request
2021-09-22 16:46:51.354 CDT [5587] LOG:  aborting any active transactions
2021-09-22 16:46:51.410 CDT [5587] LOG:  background worker "logical replication launcher" (PID 5597) exited with exit code 1
2021-09-22 16:46:51.411 CDT [5592] LOG:  shutting down
2021-09-22 16:46:51.628 CDT [5587] LOG:  database system is shut down
2021-09-22 16:47:00.384 CDT [6397] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-22 16:47:00.440 CDT [6397] LOG:  listening on IPv6 address "::1", port 5432
2021-09-22 16:47:00.440 CDT [6397] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-22 16:47:00.441 CDT [6397] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-22 16:47:01.061 CDT [6399] LOG:  database system was shut down at 2021-09-22 16:46:51 CDT
2021-09-22 16:47:01.064 CDT [6397] LOG:  database system is ready to accept connections
2021-09-23 12:07:11.276 CDT [3437] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-23 12:07:11.351 CDT [3437] LOG:  listening on IPv6 address "::1", port 5432
2021-09-23 12:07:11.351 CDT [3437] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-23 12:07:11.378 CDT [3437] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-23 12:07:11.672 CDT [3438] LOG:  database system was interrupted; last known up at 2021-09-22 20:06:00 CDT
2021-09-23 12:07:12.768 CDT [3438] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-23 12:07:12.829 CDT [3438] LOG:  redo starts at 0/17BE070
2021-09-23 12:07:12.829 CDT [3438] LOG:  invalid record length at 0/17BE158: wanted 24, got 0
2021-09-23 12:07:12.829 CDT [3438] LOG:  redo done at 0/17BE120
2021-09-23 12:07:12.916 CDT [3437] LOG:  database system is ready to accept connections
2021-09-23 18:15:48.762 CDT [7658] FATAL:  lock file "postmaster.pid" already exists
2021-09-23 18:15:48.762 CDT [7658] HINT:  Is another postmaster (PID 3437) running in data directory "/usr/local/var/postgres_dev"?
2021-09-23 18:16:02.309 CDT [3437] LOG:  received fast shutdown request
2021-09-23 18:16:02.328 CDT [3437] LOG:  aborting any active transactions
2021-09-23 18:16:02.341 CDT [4406] FATAL:  terminating connection due to administrator command
2021-09-23 18:16:02.342 CDT [3437] LOG:  background worker "logical replication launcher" (PID 3446) exited with exit code 1
2021-09-23 18:16:02.342 CDT [3441] LOG:  shutting down
2021-09-23 18:16:02.455 CDT [3437] LOG:  database system is shut down
2021-09-23 18:16:07.504 CDT [7677] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-23 18:16:07.595 CDT [7677] LOG:  listening on IPv6 address "::1", port 5432
2021-09-23 18:16:07.595 CDT [7677] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-23 18:16:07.596 CDT [7677] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-23 18:16:07.947 CDT [7678] LOG:  database system was shut down at 2021-09-23 18:16:02 CDT
2021-09-23 18:16:08.110 CDT [7677] LOG:  database system is ready to accept connections
2021-09-25 18:54:50.298 CDT [3743] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-25 18:54:52.505 CDT [3743] LOG:  listening on IPv6 address "::1", port 5432
2021-09-25 18:54:52.505 CDT [3743] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-25 18:54:52.715 CDT [3743] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-25 18:54:58.242 CDT [3754] LOG:  database system was interrupted; last known up at 2021-09-23 18:31:08 CDT
2021-09-25 18:55:10.072 CDT [3754] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-25 18:55:10.496 CDT [3754] LOG:  redo starts at 0/17E4C98
2021-09-25 18:55:10.496 CDT [3754] LOG:  invalid record length at 0/17E4D80: wanted 24, got 0
2021-09-25 18:55:10.496 CDT [3754] LOG:  redo done at 0/17E4D48
2021-09-25 18:55:11.689 CDT [3743] LOG:  database system is ready to accept connections
2021-09-26 09:37:11.218 CDT [3400] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-26 09:37:11.377 CDT [3400] LOG:  listening on IPv6 address "::1", port 5432
2021-09-26 09:37:11.377 CDT [3400] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-26 09:37:11.407 CDT [3400] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-26 09:37:11.981 CDT [3401] LOG:  database system was interrupted; last known up at 2021-09-25 18:55:11 CDT
2021-09-26 09:37:13.340 CDT [3401] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-26 09:37:13.398 CDT [3401] LOG:  redo starts at 0/17E4DF8
2021-09-26 09:37:13.398 CDT [3401] LOG:  invalid record length at 0/17E4E30: wanted 24, got 0
2021-09-26 09:37:13.398 CDT [3401] LOG:  redo done at 0/17E4DF8
2021-09-26 09:37:13.476 CDT [3400] LOG:  database system is ready to accept connections
2021-09-27 02:14:57.290 CDT [3762] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-27 02:14:57.347 CDT [3762] LOG:  listening on IPv6 address "::1", port 5432
2021-09-27 02:14:57.347 CDT [3762] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-27 02:14:57.412 CDT [3762] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-27 02:14:58.064 CDT [3765] LOG:  database system was interrupted; last known up at 2021-09-26 09:37:13 CDT
2021-09-27 02:14:59.161 CDT [3765] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-27 02:14:59.221 CDT [3765] LOG:  redo starts at 0/17E4EA8
2021-09-27 02:14:59.221 CDT [3765] LOG:  invalid record length at 0/17E4EE0: wanted 24, got 0
2021-09-27 02:14:59.221 CDT [3765] LOG:  redo done at 0/17E4EA8
2021-09-27 02:14:59.263 CDT [3762] LOG:  database system is ready to accept connections
2021-09-28 23:35:24.101 CDT [3268] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-28 23:35:24.183 CDT [3268] LOG:  listening on IPv6 address "::1", port 5432
2021-09-28 23:35:24.183 CDT [3268] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-28 23:35:24.230 CDT [3268] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-28 23:35:25.375 CDT [3269] LOG:  database system was interrupted; last known up at 2021-09-27 02:14:59 CDT
2021-09-28 23:35:27.741 CDT [3269] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-28 23:35:27.853 CDT [3269] LOG:  redo starts at 0/17E4F58
2021-09-28 23:35:27.853 CDT [3269] LOG:  invalid record length at 0/17E4F90: wanted 24, got 0
2021-09-28 23:35:27.853 CDT [3269] LOG:  redo done at 0/17E4F58
2021-09-28 23:35:28.121 CDT [3268] LOG:  database system is ready to accept connections
2021-09-29 20:33:06.667 CDT [3935] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-29 20:33:06.721 CDT [3935] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-29 20:33:06.721 CDT [3935] LOG:  listening on IPv6 address "::1", port 5432
2021-09-29 20:33:06.773 CDT [3935] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-29 20:33:07.113 CDT [3936] LOG:  database system was interrupted; last known up at 2021-09-28 23:35:28 CDT
2021-09-29 20:33:07.700 CDT [3936] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-29 20:33:07.742 CDT [3936] LOG:  redo starts at 0/17E5008
2021-09-29 20:33:07.742 CDT [3936] LOG:  invalid record length at 0/17E5040: wanted 24, got 0
2021-09-29 20:33:07.742 CDT [3936] LOG:  redo done at 0/17E5008
2021-09-29 20:33:07.785 CDT [3935] LOG:  database system is ready to accept connections
2021-09-30 02:49:03.530 CDT [3646] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-30 02:49:03.697 CDT [3646] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-30 02:49:03.698 CDT [3646] LOG:  listening on IPv6 address "::1", port 5432
2021-09-30 02:49:03.698 CDT [3646] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-30 02:49:04.193 CDT [3648] LOG:  database system was interrupted; last known up at 2021-09-29 20:33:07 CDT
2021-09-30 02:49:05.629 CDT [3648] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-30 02:49:05.632 CDT [3648] LOG:  redo starts at 0/17E50B8
2021-09-30 02:49:05.632 CDT [3648] LOG:  invalid record length at 0/17E50F0: wanted 24, got 0
2021-09-30 02:49:05.632 CDT [3648] LOG:  redo done at 0/17E50B8
2021-09-30 02:49:05.681 CDT [3646] LOG:  database system is ready to accept connections
2021-09-30 17:03:06.517 CDT [5047] LOG:  starting PostgreSQL 13.4 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
2021-09-30 17:03:06.639 CDT [5047] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2021-09-30 17:03:06.639 CDT [5047] LOG:  listening on IPv6 address "::1", port 5432
2021-09-30 17:03:06.662 CDT [5047] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2021-09-30 17:03:07.160 CDT [5048] LOG:  database system was interrupted; last known up at 2021-09-30 02:49:05 CDT
2021-09-30 17:03:08.477 CDT [5048] LOG:  database system was not properly shut down; automatic recovery in progress
2021-09-30 17:03:08.570 CDT [5048] LOG:  redo starts at 0/17E5168
2021-09-30 17:03:08.570 CDT [5048] LOG:  invalid record length at 0/17E51A0: wanted 24, got 0
2021-09-30 17:03:08.570 CDT [5048] LOG:  redo done at 0/17E5168
2021-09-30 17:03:08.635 CDT [5047] LOG:  database system is ready to accept connections
